# Generated by Django 6.0 on 2025-12-27 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendezvous', '0004_creneau'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rendezvous',
            name='date_rdv',
        ),
        migrations.RemoveField(
            model_name='rendezvous',
            name='medecin',
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='creneau',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rdv_details', to='rendezvous.creneau'),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='motif',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendezvous', to='rendezvous.patient'),
        ),
    ]
